In [3]:
import pandas as pd
import sqlite3

df = pd.read_csv("/content/Sample - Superstore.csv", encoding="latin-1")
conn = sqlite3.connect("superstore.db")
df.to_sql("orders", conn, if_exists="replace", index=False)

pd.read_sql("SELECT Category, SUM(Sales) AS total_sales, SUM(Profit) AS total_profit FROM orders GROUP BY Category", conn)

          Category  total_sales  total_profit
0        Furniture  741999.7953    18451.2728
1  Office Supplies  719047.0320   122490.8008
2       Technology  836154.0330   145454.9481

In [4]:
pd.read_sql("""
SELECT "Customer Name", ROUND(SUM(Sales), 2) AS total_spent
FROM orders
GROUP BY "Customer Name"
ORDER BY total_spent DESC
LIMIT 10
""", conn)

        Customer Name  total_spent
0         Sean Miller     25043.05
1        Tamara Chand     19052.22
2        Raymond Buch     15117.34
3        Tom Ashbrook     14595.62
4       Adrian Barton     14473.57
5        Ken Lonsdale     14175.23
6        Sanjit Chand     14142.33
7        Hunter Lopez     12873.30
8        Sanjit Engle     12209.44
9  Christopher Conant     12129.07

In [5]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Year"] = df["Order Date"].dt.year
df.to_sql("orders", conn, if_exists="replace", index=False)

pd.read_sql("""
SELECT Year, ROUND(SUM(Sales), 2) AS total_sales, ROUND(SUM(Profit), 2) AS total_profit
FROM orders
GROUP BY Year
ORDER BY Year
""", conn)

   Year  total_sales  total_profit
0  2014    484247.50      49543.97
1  2015    470532.51      61618.60
2  2016    609205.60      81795.17
3  2017    733215.26      93439.27

In [6]:
pd.read_sql("""
SELECT "Sub-Category", ROUND(SUM(Sales), 2) AS total_sales, ROUND(SUM(Profit), 2) AS total_profit
FROM orders
GROUP BY "Sub-Category"
HAVING SUM(Profit) < 0
ORDER BY total_profit
""", conn)

  Sub-Category  total_sales  total_profit
0       Tables    206965.53     -17725.48
1    Bookcases    114880.00      -3472.56
2     Supplies     46673.54      -1189.10

In [7]:
pd.read_sql("""
SELECT "Product Name", ROUND(SUM(Profit), 2) AS total_profit
FROM orders
GROUP BY "Product Name"
ORDER BY total_profit DESC
LIMIT 5
""", conn)

                                        Product Name  total_profit
0              Canon imageCLASS 2200 Advanced Copier      25199.93
1  Fellowes PB500 Electric Punch Plastic Comb Bin...       7753.04
2               Hewlett Packard LaserJet 3310 Copier       6983.88
3                 Canon PC1060 Personal Laser Copier       4570.93
4  HP Designjet T520 Inkjet Large Format Printer ...       4094.98

# Superstore SQL Analysis

## Key Insights
1. Sales grew about 1.5x from 2014 to 2017 and profit about 1.9x.
2. Profit margin rose from about 10% (2014) to about 12.7% (2017).
3. Only 3 sub-categories lose money: Tables, Bookcases and Supplies.
4. Tables have the biggest loss (-17.7K) despite over 2 lakh in sales.
5. Top customer spent over 25K. The top profit product is a Canon copier (about 25K profit).